# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Export .unitypackage from Unity Project
        # You may pin to the exact commit or the version.
        # uses: FrostBanditTeam/extract-unity-package-action@8aff23ee2b9663391db959e4b8ba3170ae276897
        uses: FrostBanditTeam/extract-unity-package-action@1
        with:
          # Path to the unity project
          unityProjectPath: ./
          # Project relative path to be packaged.
          packagePath: ./
          # Path to the output package
          outputPackagePath: ./
